version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "auto"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          update_type: "all"
